# Configuration file for Local Lumo AI
# A self-hosted, privacy-first conversational AI

# Server configuration
server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 1

# CORS configuration
cors:
  origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:8080"

# AI Models configuration
models:
  default:
    name: "Default Model"
    type: "echo"  # placeholder for actual model type
    enabled: true
    max_tokens: 2048
    temperature: 0.7

# Database configuration (for future use)
database:
  type: "sqlite"
  path: "data/conversations.db"
  echo: false

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"

# Security configuration
security:
  enable_auth: false  # Set to true when implementing authentication
  jwt_secret: "your-secret-key-here"  # Change in production
  session_timeout: 3600  # seconds

# Privacy settings
privacy:
  store_conversations: true
  encrypt_data: false  # Set to true for enhanced privacy
  retention_days: 30

# Plugin configuration
plugins:
  enabled: true
  directory: "plugins"
  auto_load: true

# Performance settings
performance:
  max_concurrent_requests: 10
  request_timeout: 30  # seconds
  cache_enabled: true
  cache_ttl: 300  # seconds